# This is a my first Github Actions Workflow

name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create build
        run: echo "Created build Job"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test cases
        run: echo "Check full test case coverage"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        run: echo "Ready to Deploy"
